settings:
  title: 'Status Page'
  url: 'https://status-page.yanwei.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: localbond-prod # unique identifier
    name: localbond Web prod
    description: 'localbond prod env' # default=empty
    url: 'https://admin.localbond.tw/login' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: localbond-API-prod # unique identifier
    name: localbond API prod
    description: 'localbond API prod env' # default=empty
    url: 'https://api.localbond.tw/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: yowoo-shortlink-prod # unique identifier
    name: yowoo短網址
    description: 'yowoo短網址' # default=empty
    url: 'https://link.yo-woo.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 400 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: api-proxy-localbond-prod # unique identifier
    name: localbond proxy api prod
    description: 'api proxy for kgi prod env' # default=empty
    url: 'https://api-proxy.localbond.tw' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: bi-localbond-prod # unique identifier
    name: localbond bi
    description: 'localbond bi' # default=empty
    url: 'https://bi.yo-woo.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
